# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralbum',
            name='photo',
            field=models.ImageField(upload_to='/home/denis/side_projects/justapic/upload_images'),
        ),
    ]
